#!/bin/sh

help()
{
	echo "OPTIONS:"
	echo "  start"
	echo "  update"
}

update()
{
	cd /harvey
	git pull
	if [ $? -eq 0 ]
	then
		./bootstrap.sh
		/harvey/util/build
	else
		exit 1
	fi
}


if [ -z "$1" ]
then
	help
  exit 1
fi

case "$1" in
	start)
		if [ ! -f /harvey/sys/src/9/amd64/harvey.32bit ]
		then
			update
		fi
		/harvey/util/GO9PCPU
		;;
	update)
		update
		;;
	*)
	  echo "Error param: $1"
		exit 1
		;;
esac
